[package]
name = "dimooper"
version = "0.1.0"
authors = ["rexim <reximkut@gmail.com>"]

[dependencies]
# FIXME(#160): fix build with clippy
# clippy = "0.0.89"
portmidi = "^0.2"
num = "0.1.32"
sdl2 = "0.21"
sdl2_ttf = "0.21"
